import { Sidebar } from "@/components/Sidebar";
import { useAlerts } from "@/hooks/use-dashboard";
import { StatusBadge } from "@/components/StatusBadge";
import { AlertTriangle, Bell, Info, ShieldAlert } from "lucide-react";
import { formatDistanceToNow } from "date-fns";
import { type Alert } from "@shared/schema";
import { cn } from "@/lib/utils";

export default function AlertsPage() {
  const { data: alerts, isLoading } = useAlerts();

  const getIcon = (severity: string) => {
    switch(severity) {
      case 'CRITICAL': return ShieldAlert;
      case 'HIGH': return AlertTriangle;
      case 'MEDIUM': return Bell;
      default: return Info;
    }
  };

  const getColor = (severity: string) => {
    switch(severity) {
      case 'CRITICAL': return "text-red-500 bg-red-500/10 border-red-500/20";
      case 'HIGH': return "text-orange-500 bg-orange-500/10 border-orange-500/20";
      case 'MEDIUM': return "text-amber-500 bg-amber-500/10 border-amber-500/20";
      default: return "text-blue-500 bg-blue-500/10 border-blue-500/20";
    }
  };

  return (
    <div className="flex min-h-screen bg-background text-foreground">
      <Sidebar />
      <main className="flex-1 ml-64 p-8 overflow-y-auto">
        <div className="mb-8">
          <h1 className="text-3xl font-display font-bold">System Alerts</h1>
          <p className="text-muted-foreground mt-1">Notifications generated by the Sentinel AI agent</p>
        </div>

        <div className="space-y-4 max-w-4xl">
          {isLoading ? (
            <div className="text-center py-12 text-muted-foreground">Loading alerts...</div>
          ) : (
            alerts?.map((alert: Alert) => {
              const Icon = getIcon(alert.severity);
              const colorClass = getColor(alert.severity);
              
              return (
                <div 
                  key={alert.id} 
                  className="glass-card p-6 rounded-xl flex items-start gap-4 hover:bg-card/80 transition-colors"
                >
                  <div className={cn("p-3 rounded-lg border", colorClass)}>
                    <Icon className="h-6 w-6" />
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center justify-between mb-1">
                      <h3 className="font-semibold text-lg">{alert.severity} Alert</h3>
                      <span className="text-xs text-muted-foreground font-mono">
                        {formatDistanceToNow(new Date(alert.timestamp), { addSuffix: true })}
                      </span>
                    </div>
                    <p className="text-muted-foreground">{alert.message}</p>
                  </div>
                  {!alert.isRead && (
                    <div className="h-3 w-3 bg-primary rounded-full mt-2" />
                  )}
                </div>
              );
            })
          )}
          
          {alerts?.length === 0 && (
            <div className="text-center py-12 glass-card rounded-xl">
              <Bell className="h-12 w-12 text-muted-foreground mx-auto mb-4 opacity-20" />
              <h3 className="text-lg font-medium">No alerts</h3>
              <p className="text-muted-foreground">System is running smoothly.</p>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
